const currencies = [
  { 
      code: 'USD', 
      name: 'Dólar dos Estados Unidos', 
      flag: 'iVBORw0KGgoAAAANSUhEUgAAAAoAAAALCAYAAACpLQ5NAAAACXBIWXMAAAsTAAALEwEAmpwYAAAA60lEQVR42o2PwQnCQBRE37/VNYdK2LEnMVIbN5IbCoU7CFq2vYEgOS3hJC42UE+HQTzHXeu3j3/TGcgLk/JN/sz/s3+z/cP6h8j3qAayr3WkxihCmNQ2P2bo9nBtrMl8UwOcsQatMIpuPBC0xBV5GzHcs+jeJ7qSHaqQFQIC4YngXIOiVxRUlgcdg8czY7UEixGmVDPJBSNEF2lvCePfLWyqQaov4LMqXKyRQOIJkHPL2TuqaT9z/iJpBNdzPeX9oM17PAj+G9AlhTu8ZLAAAAgF4AAAABJRU5ErkJggg==' 
  },
  { 
      code: 'EUR', 
      name: 'Euro', 
      flag: 'iVBORw0KGgoAAAANSUhEUgAAAAoAAAALCAYAAACpLQ5NAAAACXBIWXMAAAsTAAALEwEAmpwYAAAA10lEQVR42mNgoAhqzrz18PQ/29FNjCxMRAQSiq5lZSh+3t7XZ4cHl5OTgI2cYHAqLP7+/vwMQFVVVVWhIIpdCpCiMmLi4h+Pi4g8JDAtLAZ8fn2MRWNjY8MJCYpaWlhYZGRkwMRkDJQ1ICymZmZGQAH5w9aAMkLAZsbOzy89A2kTA4ZQVABEMcDAxAYiFlaGho4BMwbQCbESkCE9v399gNkbGxswM5wCTQEm4jRoCrRkcXGxg1Ek9IjRQEAK+mJefG2KoEAAAAASUVORK5CYII=' 
  },
  { 
      code: 'JPY', 
      name: 'Iene Japonês', 
      flag: 'iVBORw0KGgoAAAANSUhEUgAAAAoAAAALCAYAAACpLQ5NAAAACXBIWXMAAAsTAAALEwEAmpwYAAAA9ElEQVR42mNgoBpgFOOefPH0CRH1v6rqGJkZHxKyMiTH+CAu5/DHjXH0DLCEPCgKioqxFzKLU3NzcvAIKgIBGbYOTn5y9fBPcXVFXA7NBJ4+/at2/sHh4en/f29vYxLCgoKP8bBhAjkWcEITRZXV9f/9YgKwNTkXADrwgBqaWlp//9HnHx8nH5gFBTIDGAmrGbNj+KiPpmoBKMj0gBJRZAk5eLiIv4FQvUCsyUjFikT3EYjGfn396xMwMBACibEqEjJlNQUmjFQADDOIbZkAK7sAAAAASUVORK5CYII=' 
  },
  { 
      code: 'GBP', 
      name: 'Libra Esterlina', 
      flag: 'iVBORw0KGgoAAAANSUhEUgAAAAoAAAALCAYAAACpLQ5NAAAACXBIWXMAAAsTAAALEwEAmpwYAAAA5ElEQVR42mNgoAq4dfnx8/MPKRhzW1tZaQxhFOTl52CzMxMVDwzzsQEpKSk7MjIzKFYgIvJzczMzC1GV1dXvxsYHh4eBfUMRiIle5ubmPEsLAyB1FxcX/8cYJCD2IFJHxiOjrbVpqKjkAz//fYBHEUUP6kR6F1IZ2tpa/8JAKQmJqZm/gXJxcXGEIFkAM//hwQUFPysFZZkJalZWTlgwEUmFB7Pnvnzp19+Pi4hcAJTCwb/z/XKzs5F9WZmZmVvBKhCQgxABLMn6GhEZiQAAAABJRU5ErkJggg==' 
  },
  { 
      code: 'AUD', 
      name: 'Dólar Australiano', 
      flag: 'iVBORw0KGgoAAAANSUhEUgAAAAoAAAALCAYAAACpLQ5NAAAACXBIWXMAAAsTAAALEwEAmpwYAAAA5klEQVR42mNgoAow+a1evZsOJPCPq6ure0dEhLCwsnH+BjIykZjZGb4wsPDH1ATk6OCihBPYODg4wcTExMX9GR0ebAxkZGdnU3Jzf2XsmzYM7O/sHBYGpqCmD2AM4DKCS0tbX//2JD7IyMi/qjoEkJ9/79+jWICsDU5FwA68IAam1tbW//0ScfHz8AfqBQSMwJqRmzY/isz5pqASjI9IASUWQJKTn5+f+BUL1ArMlIxYpE9xGIxn5//frEzAwEAKJ5bRpuj1uFAAAAAElFTkSuQmCC' 
  },
  { 
      code: 'CAD', 
      name: 'Dólar Canadense', 
      flag: 'iVBORw0KGgoAAAANSUhEUgAAAAoAAAALCAYAAACpLQ5NAAAACXBIWXMAAAsTAAALEwEAmpwYAAAA4ElEQVR42mNgoBY4T/39/bGFR4MTMxNG5eXl+nEZ2dnf8IMQFVVVVWhIFpCpCiMyOCgoKPyKQEJKyMzMzCBIkPJSAsMDAwAMgLS6iAKkG/ffq0//o0atWrbfu+/cPn78O6Knp5eDNDxcXF/AwImkUFmEITTYX19v/8qAvJSUVjY/gkPl6enspqAcTAWEAK9+ODg77/+cWXl5cPkDQRcT2AChTSbWlP+BIRExNKZN1G4z5jZ2entMDGRgYmKnEiG9SAQBd2j1xfwocNAAAAAElFTkSuQmCC' 
  },
  { 
      code: 'CHF', 
      name: 'Franco Suíço', 
      flag: 'iVBORw0KGgoAAAANSUhEUgAAAAoAAAALCAYAAACpLQ5NAAAACXBIWXMAAAsTAAALEwEAmpwYAAAA+klEQVR42mNgoBcI5evXr29DGRn1//E4Nm2bgYKECazMzNlsMJZSEpJ/mZycDMCcQoLCyMAyIiZmZlFZB9xcXF/AcTExMMQFVVVVWhIIpXyFFsQGEFkJmZmaAiMP5+eVGZmZmzhIlEgpCIoYcUqSlpZWQFAVpaGiAqI5uTl59dfBLw8PDf8UEpLQqogBYk0qgMDg5O0AWQE5Ozu/MvAQEliF6OSMQHYkUtm4/3MDGRgY1Eg3EiAkAMUzLSUS4LaGAAAAAElFTkSuQmCC' 
  },
  { 
      code: 'CNY', 
      name: 'Yuan Chinês', 
      flag: 'iVBORw0KGgoAAAANSUhEUgAAAAoAAAALCAYAAACpLQ5NAAAACXBIWXMAAAsTAAALEwEAmpwYAAAA6klEQVR42mNgoAhqzrx18vQD/f///3UswMxMSkZGSzGFCopOTn52M3MzNRhJSUl/2RhAig0FYdAODs7+6NkA2NjY+MSAoaWlpSPAMQUFCuP7+/swMFhUVDcBamJicdUWS7NLS0v8ZBBk5OjoE2GNiYmL/EEDHSmho6J+FBKyYQQBNI1O3bt38BoISImBhAwMjIC8P8gKT2//vcVAEUz3Bv/QYCIURSDHA2AALan6GiSSGzgAAAABJRU5ErkJggg==' 
  },
  { 
      code: 'SEK', 
      name: 'Coroa Sueca', 
      flag: 'iVBORw0KGgoAAAANSUhEUgAAAAoAAAALCAYAAACpLQ5NAAAACXBIWXMAAAsTAAALEwEAmpwYAAAA4ElEQVR42mNgoCcI5evXr29DGRn1/X9LSwsTB1VQX5ZMzMxMfViOjn5+fmWgIpGRkZ/haYE1NTX/D4LhGJt1wMDBAwOgoKC8jEAsLS3PzEBAogEYkJFReXl5vhkAq6np6UE2QSktLS/9HBD+VlZUNwEqEQSGDshArUUlO/v7yMiUEmZ3d/+GFBayYQQBLI1O3bt3/7MBdA5KIAsFMSgMLCws/5eLk6cATWJ0BFU0MyBUQAP4+v0sAfFS9wAAAAASUVORK5CYII=' 
  },
  { 
      code: 'NZD', 
      name: 'Dólar Neozelandês', 
      flag: 'iVBORw0KGgoAAAANSUhEUgAAAAoAAAALCAYAAACpLQ5NAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAtElEQVR42mNgoAqIMe1evXsOK8dVVVWxMTAxgZWUlZWLouL1/f//+bxPD7ABAkK/v7+N0KIQzFDRUVFQHHdHS0lx0HLTy8nIUQQJXPDw8P8CUAEtLS+MVKIJCW5mZ/pkERUdHt0AmCEgWzRAFGChADKqTk5NkA0gP5GZDPM8AfEXcP/Lhw8fsQ5T9MPv7+yRKBkCVQyGJiYm/KW9np6fAWACckQZUAalXwAAAABJRU5ErkJggg==' 
  },
  { 
      code: 'BRL', 
      name: 'Real Brasileiro', 
      flag: 'iVBORw0KGgoAAAANSUhEUgAAAAoAAAALCAYAAACpLQ5NAAAACXBIWXMAAAsTAAALEwEAmpwYAAAA0klEQVR42mNgoAUY5/f379/DMScdXV2dMTDRHwLMCU5OTj52MwMDQ1iSUlJ/2RkAipGQVFRX+ECySMXNTV11DsCChFJRUECrUlpaysrK/gkAAM/JSQHBzMyMizF7OzsPAPISgpCCocQlRIcAP/ZHEAQUtLS/8vA2AhFAEr8EFNBUhNTU0eEDE1NeX80QAkqMywARxPbNnDA4YyAJKHAsXHxMYYCJUU1MjA8HAAKzexkB9CROkAAAAAElFTkSuQmCC' 
  }
];
  
  module.exports = currencies;
  